# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.2
minimum_travel_heading: 0.174             #in radians
scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 20.0
# use_scan_range: 20

# Correlation Parameters - Correlation Parameters
# smear_deviation Must be between [0.5 * resolution, 10 * resolution]
correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

# Scan Matcher Parameters
distance_variance_penalty: 0.3              # gets squared later
angle_variance_penalty: 0.349              # in degrees (gets converted to radians then squared)
fine_search_angle_offset: 0.00349               # in degrees (gets converted to radians)
coarse_search_angle_offset: 0.349            # in degrees (gets converted to radians)
coarse_angle_resolution: 0.0349                # in degrees (gets converted to radians)
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false

# back-end
use_back_end: true     # 是否启用后端优化
do_loop_closing: true  # 是否启用回环检测
marker_count: 0
solver_type: ceres_solver # spa_solver, gtsam_solver, g2o_solver, ceres_solver

# Correlation Parameters - Loop Closure Parameters
# smear_deviation Must be between [0.5 * resolution, 10 * resolution]
loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03

link_match_minimum_response_fine: 0.5
link_scan_maximum_distance: 10.0
loop_search_maximum_distance: 4.0

loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.4     # gets squared later
loop_match_minimum_response_coarse: 0.5
loop_match_minimum_response_fine: 0.5

map_update_interval: 5

